name: Scrape Talent Tickets

on:
  workflow_dispatch:  # 手動実行可
  schedule:
    - cron:  '3 9,17,23 * * *'  # 9時,17時,23時(JST+9)に実行（例）

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          TALENT_BASE_URL: https://profile.yoshimoto.co.jp/talent/detail?id=
        run: python talent_tickets.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: talent_tickets_csv
          path: talent_tickets.csv

      - name: Setup credentials.json
        run: echo "${{ secrets.GSHEET_CREDENTIALS_JSON }}" | base64 -d > credentials.json

      - name: Notify new events by email
        env:
          GSHEET_URL: ${{ secrets.GSHEET_URL }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: python notify_new_events.py

      - name: Upload to Google Sheets
        env:
          GSHEET_URL: ${{ secrets.GSHEET_URL }}
        run: python update_sheet.py

      - name: Convert CSV to JSON
        run: python csv_to_json.py

      - name: Configure Git and PAT
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      # 画像アップロードCommit
      - name: Git add/push images for Pages
        run: |
          git add docs/img/flier 
          git commit -m "Update event images" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Git add/push JSON data
        run: |
          git add docs/data/talent_schedules.json
          git commit -m "Update talent_schedules.json" || echo "No changes to commit"
          git push || echo "No changes to push"
